import { BellRing, Check, CirclePlus, Download, FileSpreadsheet, FileText, FlaskConical, PlugZap, RefreshCw, Save, Search, Server, ShieldCheck, SlidersHorizontal, UserPlus, Wifi } from "lucide-react";
import { type FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { api, download, formatDate } from "../api";
import { useAuth } from "../auth";
import { Badge, Empty, ErrorNotice, Metric, PageHeader, Pagination, Panel, Spinner } from "../components/ui";
import type { Alert, Channel, Device, PageResult, Session } from "../types";

export function DevicesPage() {
  const { user } = useAuth(); const [devices, setDevices] = useState<Device[]>([]); const [statuses, setStatuses] = useState<Record<number, any>>({}); const [test, setTest] = useState<any>(null); const [showCreate, setShowCreate] = useState(false); const [error, setError] = useState("");
  const load = useCallback(() => api<Device[]>("/devices").then((rows) => { setDevices(rows); rows.forEach((device) => api<any>(`/devices/${device.id}/status`).then((status) => setStatuses((current) => ({ ...current, [device.id]: status })))); }).catch((err) => setError(err.message)), []);
  useEffect(() => { void load(); }, [load]);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); try { await api("/devices", { method: "POST", body: JSON.stringify({ name: data.get("name"), manufacturer: data.get("manufacturer") || null, model: data.get("model") || null, serial_number: data.get("serial") || null, connection_type: data.get("connection"), protocol: data.get("protocol"), port: data.get("port") || null, baud_rate: Number(data.get("baud")), active: true, metadata: {} }) }); setShowCreate(false); load(); } catch (err) { setError(err instanceof Error ? err.message : "Falha"); } }
  async function testConnection(id: number) { setTest({ loading: true }); try { setTest(await api(`/devices/${id}/test`, { method: "POST" })); } catch (err) { setTest({ error: err instanceof Error ? err.message : "Falha" }); } }
  async function toggleConnection(device: Device) { try { const connected = statuses[device.id]?.connected; if (connected) { await api(`/devices/${device.id}/disconnect`, { method: "POST" }); } else { await api(`/devices/${device.id}/connect`, { method: "POST" }); } load(); } catch (err) { setError(err instanceof Error ? err.message : "Falha"); } }
  return <><PageHeader eyebrow="INTEGRAÇÃO DE HARDWARE" title="Equipamentos" description="Cadastre fontes de aquisição, teste a comunicação e acompanhe o estado." actions={user?.role === "admin" && <button className="button primary" onClick={() => setShowCreate(true)}><CirclePlus/> Novo equipamento</button>}/>{error && <ErrorNotice message={error}/>}<div className="device-grid">{devices.map((device) => { const status = statuses[device.id] ?? { state: "disconnected" }; return <Panel key={device.id} className="device-card"><div className="device-card-top"><span className={`device-icon ${status.connected ? "connected" : ""}`}><Server/></span><Badge tone={status.connected ? "success" : "neutral"}>{status.connected ? "Conectado" : "Desconectado"}</Badge></div><h2>{device.name}</h2><p>{device.manufacturer || "Fabricante não informado"} · {device.model || "Modelo não informado"}</p><div className="device-specs"><div><span>PROTOCOLO</span><strong>{device.protocol}</strong></div><div><span>PORTA</span><strong>{device.port || "Virtual"}</strong></div><div><span>BAUD RATE</span><strong>{device.baud_rate.toLocaleString("pt-BR")}</strong></div><div><span>ÚLTIMA CONEXÃO</span><strong>{formatDate(device.last_connected_at)}</strong></div></div><div className="device-actions"><button className="button secondary" onClick={() => testConnection(device.id)}><FlaskConical/> Testar conexão</button>{user?.role !== "viewer" && <button className="button ghost" onClick={() => toggleConnection(device)}><PlugZap/> {status.connected ? "Desconectar" : "Conectar"}</button>}</div></Panel>; })}</div>
    {test && <Panel title="Resultado do teste" kicker="DIAGNÓSTICO DE COMUNICAÇÃO" actions={<button className="icon-button" onClick={() => setTest(null)}>×</button>}>{test.loading ? <Spinner label="Abrindo porta e aguardando leitura"/> : test.error ? <ErrorNotice message={test.error}/> : <div className="test-grid"><div><Badge tone={test.port_open ? "success" : "danger"}>{test.port_open ? "OK" : "Falha"}</Badge><span>Porta aberta</span></div><div><Badge tone={test.data_received ? "success" : "danger"}>{test.data_received ? "OK" : "Falha"}</Badge><span>Dados recebidos</span></div><div><Badge tone={test.format_recognized ? "success" : "danger"}>{test.format_recognized ? "OK" : "Falha"}</Badge><span>Formato reconhecido</span></div><div><strong>{test.approximate_frequency_hz.toFixed(2)} Hz</strong><span>Frequência aproximada</span></div><div><strong>{test.detected_channels}</strong><span>Canais detectados</span></div><div><strong>{test.errors}</strong><span>Erros encontrados</span></div></div>}</Panel>}
    {showCreate && <div className="modal-backdrop" onMouseDown={() => setShowCreate(false)}><form className="modal" onSubmit={create} onMouseDown={(e) => e.stopPropagation()}><div className="modal-head"><div><p className="eyebrow">CADASTRO</p><h2>Novo equipamento</h2></div><button type="button" onClick={() => setShowCreate(false)}>×</button></div><div className="form-grid"><label className="field"><span>Nome</span><input name="name" required/></label><label className="field"><span>Fabricante</span><input name="manufacturer"/></label><label className="field"><span>Modelo</span><input name="model"/></label><label className="field"><span>Número de série</span><input name="serial"/></label><label className="field"><span>Conexão</span><select name="connection"><option value="simulator">Simulador</option><option value="serial">Serial / USB</option></select></label><label className="field"><span>Protocolo</span><select name="protocol"><option value="simulator">Simulador</option><option value="at4532_serial">Applent AT4532 (aguarda homologação)</option><option value="gpm8213_serial">GW Instek GPM-8213 (aguarda homologação)</option><option value="serial_json">Serial JSON</option><option value="serial_csv">Serial CSV (não homologado)</option><option value="mock_failure">Falha de teste</option></select></label><label className="field"><span>Porta</span><input name="port" placeholder="COM3"/></label><label className="field"><span>Baud rate</span><select name="baud" defaultValue="115200"><option>9600</option><option>19200</option><option>57600</option><option>115200</option></select></label></div><p className="hint">Portas físicas e protocolos dependem da homologação do aquisitor.</p><div className="modal-actions"><button type="button" className="button ghost" onClick={() => setShowCreate(false)}>Cancelar</button><button className="button primary"><Save/> Salvar</button></div></form></div>}
  </>;
}

export function ChannelsPage() {
  const { user } = useAuth(); const [devices, setDevices] = useState<Device[]>([]); const [deviceId, setDeviceId] = useState(0); const [channels, setChannels] = useState<Channel[]>([]); const [profiles, setProfiles] = useState<any[]>([]); const [editing, setEditing] = useState<Channel | null>(null); const [error, setError] = useState("");
  useEffect(() => { api<Device[]>("/devices").then((rows) => { setDevices(rows); if (rows[0]) setDeviceId(rows[0].id); }); api<any[]>("/channel-profiles").then(setProfiles); }, []);
  const load = useCallback(() => { if (deviceId) api<Channel[]>(`/devices/${deviceId}/channels`).then(setChannels).catch((err) => setError(err.message)); }, [deviceId]); useEffect(() => { void load(); }, [load]);
  async function toggle(channel: Channel) { await save({ ...channel, enabled: !channel.enabled }); }
  async function save(channel: Channel) { try { await api(`/devices/${deviceId}/channels/${channel.channel}`, { method: "PUT", body: JSON.stringify(channel) }); setEditing(null); load(); } catch (err) { setError(err instanceof Error ? err.message : "Falha"); } }
  async function saveProfile() { const name = prompt("Nome do novo perfil de canais:"); if (!name) return; try { await api("/channel-profiles", { method:"POST", body:JSON.stringify({ name, channels }) }); setProfiles(await api<any[]>("/channel-profiles")); } catch (err) { setError(err instanceof Error ? err.message : "Falha"); } }
  async function applyProfile(profileId: number) { if (!profileId) return; try { await api(`/channel-profiles/${profileId}/apply/${deviceId}`, { method:"POST" }); load(); } catch (err) { setError(err instanceof Error ? err.message : "Falha"); } }
  return <><PageHeader eyebrow="CONFIGURAÇÃO DE ENTRADAS" title="Termopares" description="Identifique, calibre e defina limites para até 32 canais." actions={<><label className="compact-field"><span>Equipamento</span><select value={deviceId} onChange={(e) => setDeviceId(Number(e.target.value))}>{devices.map((device) => <option key={device.id} value={device.id}>{device.name}</option>)}</select></label>{user?.role !== "viewer" && <><label className="compact-field"><span>Aplicar perfil</span><select defaultValue="" onChange={(e) => applyProfile(Number(e.target.value))}><option value="">Selecionar</option>{profiles.map((profile) => <option key={profile.id} value={profile.id}>{profile.name}</option>)}</select></label><button className="button secondary" onClick={saveProfile}><Save/> Salvar perfil</button></>}</>}/>{error && <ErrorNotice message={error}/>}<div className="channels-grid">{channels.map((channel) => <article className={`channel-card ${channel.enabled ? "enabled" : ""}`} key={channel.id}><div className="channel-head"><span style={{ background: channel.color }}>T{channel.channel}</span>{user?.role !== "viewer" && <button className={`switch ${channel.enabled ? "on" : ""}`} onClick={() => toggle(channel)} aria-label={`${channel.enabled ? "Desativar" : "Ativar"} T${channel.channel}`}/>}</div><h3>{channel.name}</h3><strong className="channel-limit">{channel.critical_limit != null ? `${channel.critical_limit.toFixed(1)} °C` : "Sem limite"}</strong><small>Limite crítico</small><div className="channel-meta"><span>Tipo {channel.sensor_type}</span><span>Offset {channel.correction_offset >= 0 ? "+" : ""}{channel.correction_offset}°</span></div>{user?.role !== "viewer" && <button className="button ghost full" onClick={() => setEditing(channel)}><SlidersHorizontal/> Configurar</button>}</article>)}</div>
    {editing && <div className="modal-backdrop" onMouseDown={() => setEditing(null)}><form className="modal wide" onSubmit={(event) => { event.preventDefault(); save(editing); }} onMouseDown={(e) => e.stopPropagation()}><div className="modal-head"><div><p className="eyebrow">TERMOPAR T{editing.channel}</p><h2>Configurar canal</h2></div><button type="button" onClick={() => setEditing(null)}>×</button></div><div className="form-grid"><label className="field"><span>Nome</span><input value={editing.name} onChange={(e) => setEditing({...editing, name:e.target.value})}/></label><label className="field"><span>Tipo de termopar</span><select value={editing.sensor_type} onChange={(e) => setEditing({...editing, sensor_type:e.target.value})}>{["K","J","T","E","N","R","S","B"].map((type)=><option key={type}>{type}</option>)}</select></label><label className="field"><span>Unidade</span><select value="°C" disabled><option>°C</option></select></label><label className="field"><span>Offset de calibração</span><input type="number" step="0.1" value={editing.correction_offset} onChange={(e) => setEditing({...editing, correction_offset:Number(e.target.value)})}/></label><label className="field"><span>Limite de atenção</span><input type="number" step="0.1" value={editing.warning_limit ?? ""} onChange={(e) => setEditing({...editing, warning_limit:Number(e.target.value)})}/></label><label className="field"><span>Limite crítico</span><input type="number" step="0.1" value={editing.critical_limit ?? ""} onChange={(e) => setEditing({...editing, critical_limit:Number(e.target.value)})}/></label><label className="field"><span>Cor no gráfico</span><input type="color" value={editing.color} onChange={(e) => setEditing({...editing, color:e.target.value})}/></label><label className="field"><span>Localização física</span><input value={editing.physical_location ?? ""} onChange={(e) => setEditing({...editing, physical_location:e.target.value})}/></label><label className="field"><span>Ordem de exibição</span><input type="number" min="0" max="32" value={editing.display_order ?? editing.channel} onChange={(e) => setEditing({...editing, display_order:Number(e.target.value)})}/></label></div><label className="field"><span>Descrição</span><textarea rows={3} value={editing.description ?? ""} onChange={(e) => setEditing({...editing, description:e.target.value})}/></label><div className="modal-actions"><button type="button" className="button ghost" onClick={() => setEditing(null)}>Cancelar</button><button className="button primary"><Save/> Salvar canal</button></div></form></div>}
  </>;
}

export function AlertsPage() {
  const { user } = useAuth(); const [result, setResult] = useState<PageResult<Alert> | null>(null); const [rules, setRules] = useState<any[]>([]); const [devices, setDevices] = useState<Device[]>([]); const [page, setPage] = useState(1); const [severity, setSeverity] = useState(""); const [ack, setAck] = useState(""); const [showRule, setShowRule] = useState(false); const [error, setError] = useState("");
  const load = useCallback(() => Promise.all([api<PageResult<Alert>>(`/alerts?page=${page}&page_size=25&severity=${severity}${ack ? `&acknowledged=${ack}` : ""}`), api<any[]>("/alert-rules"), api<Device[]>("/devices")]).then(([alerts, allRules, allDevices]) => { setResult(alerts); setRules(allRules); setDevices(allDevices); }).catch((err) => setError(err.message)), [page,severity,ack]); useEffect(() => { void load(); }, [load]);
  async function acknowledge(id: number) { await api(`/alerts/${id}/acknowledge`, { method:"POST" }); load(); }
  async function createRule(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); await api("/alert-rules", { method:"POST", body:JSON.stringify({ device_id:Number(data.get("device")), metric:data.get("metric"), channel:data.get("channel") ? Number(data.get("channel")) : null, operator:data.get("operator"), threshold:Number(data.get("threshold")), severity:data.get("severity"), cooldown_seconds:Number(data.get("cooldown")), enabled:true })}); setShowRule(false); load(); }
  return <><PageHeader eyebrow="CENTRAL DE OCORRÊNCIAS" title="Alertas" description="Violações com severidade, reconhecimento e proteção contra repetição." actions={user?.role === "admin" && <button className="button primary" onClick={()=>setShowRule(true)}><CirclePlus/> Nova regra</button>}/>{error && <ErrorNotice message={error}/>}<div className="metrics-grid four"><Metric label="Alertas exibidos" value={result?.total ?? 0}/><Metric label="Não reconhecidos" value={result?.items.filter((a)=>!a.acknowledged).length ?? 0} tone="danger"/><Metric label="Regras configuradas" value={rules.length}/><Metric label="Cooldown mínimo" value={`${Math.min(...rules.map((r)=>r.cooldown_seconds),0)} s`} /></div><Panel className="filter-panel"><div className="filters"><label><select value={severity} onChange={(e)=>setSeverity(e.target.value)}><option value="">Todas as severidades</option><option value="critical">Crítico</option><option value="warning">Atenção</option><option value="info">Informação</option></select></label><label><select value={ack} onChange={(e)=>setAck(e.target.value)}><option value="">Todos</option><option value="false">Ativos</option><option value="true">Reconhecidos</option></select></label></div></Panel><Panel className="table-panel">{!result ? <Spinner/> : !result.items.length ? <Empty title="Nenhum alerta encontrado"/> : <div className="table-scroll"><table><thead><tr><th>Severidade</th><th>Horário</th><th>Sessão</th><th>Métrica</th><th>Canal</th><th>Valor medido</th><th>Limite</th><th>Status</th><th/></tr></thead><tbody>{result.items.map((alert)=><tr key={alert.id}><td><Badge tone={alert.severity === "critical" ? "danger":"warning"}>{alert.severity}</Badge></td><td>{formatDate(alert.timestamp)}</td><td>#{alert.session_id}</td><td>{alert.metric === "power" ? "Potência":"Temperatura"}</td><td>{alert.channel ? `T${alert.channel}`:"—"}</td><td><strong>{alert.measured_value.toFixed(2)}</strong></td><td>{alert.threshold.toFixed(2)}</td><td><Badge tone={alert.acknowledged ? "neutral":"danger"}>{alert.acknowledged ? "Reconhecido":"Ativo"}</Badge></td><td>{!alert.acknowledged && user?.role !== "viewer" && <button className="button small secondary" onClick={()=>acknowledge(alert.id)}><Check/> Reconhecer</button>}</td></tr>)}</tbody></table></div>}{result && <Pagination page={result.page} pages={result.pages} total={result.total} onChange={setPage}/>}</Panel>
    {showRule && <div className="modal-backdrop" onMouseDown={()=>setShowRule(false)}><form className="modal" onSubmit={createRule} onMouseDown={(e)=>e.stopPropagation()}><div className="modal-head"><div><p className="eyebrow">AUTOMAÇÃO</p><h2>Nova regra de alerta</h2></div><button type="button" onClick={()=>setShowRule(false)}>×</button></div><label className="field"><span>Equipamento</span><select name="device">{devices.map((d)=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><div className="form-grid"><label className="field"><span>Métrica</span><select name="metric"><option value="temperature">Temperatura</option><option value="power">Potência</option></select></label><label className="field"><span>Canal (opcional)</span><input name="channel" type="number" min="1" max="32"/></label><label className="field"><span>Operador</span><select name="operator"><option>&gt;</option><option>&gt;=</option><option>&lt;</option><option>&lt;=</option></select></label><label className="field"><span>Limite</span><input name="threshold" type="number" step="0.1" required/></label><label className="field"><span>Severidade</span><select name="severity"><option value="warning">Atenção</option><option value="critical">Crítico</option><option value="info">Informação</option></select></label><label className="field"><span>Cooldown (s)</span><input name="cooldown" type="number" defaultValue="60" min="1"/></label></div><div className="modal-actions"><button className="button primary"><Save/> Criar regra</button></div></form></div>}
  </>;
}

export function EventsPage() {
  const [result,setResult]=useState<PageResult<any>|null>(null); const [page,setPage]=useState(1); const [level,setLevel]=useState(""); const [category,setCategory]=useState(""); const [search,setSearch]=useState("");
  const load=useCallback(()=>api<PageResult<any>>(`/events?page=${page}&page_size=40&level=${level}&category=${category}&search=${encodeURIComponent(search)}`).then(setResult),[page,level,category,search]); useEffect(()=>{void load();},[load]);
  return <><PageHeader eyebrow="RASTREABILIDADE" title="Eventos e logs" description="Auditoria de conexões, sessões, falhas e alterações operacionais."/><Panel className="filter-panel"><div className="filters"><label className="search-field"><Search/><input placeholder="Pesquisar mensagem" value={search} onChange={(e)=>setSearch(e.target.value)}/></label><label><select value={level} onChange={(e)=>setLevel(e.target.value)}><option value="">Todos os níveis</option><option value="info">Informação</option><option value="warning">Atenção</option><option value="error">Erro</option></select></label><label><select value={category} onChange={(e)=>setCategory(e.target.value)}><option value="">Todas as categorias</option><option value="connection">Conexão</option><option value="disconnection">Desconexão</option><option value="login">Login</option><option value="session_start">Sessão</option><option value="configuration">Configuração</option><option value="read_error">Leitura</option></select></label></div></Panel><Panel>{!result ? <Spinner/> : !result.items.length ? <Empty/> : <div className="timeline">{result.items.map((event)=><div key={event.id}><span className={`timeline-dot ${event.level}`}/><time>{formatDate(event.timestamp)}</time><Badge tone={event.level === "error" ? "danger": event.level === "warning" ? "warning":"neutral"}>{event.category}</Badge><div><strong>{event.message}</strong><small>{event.device_id ? `Equipamento #${event.device_id}`:"Sistema"}{event.session_id ? ` · Sessão #${event.session_id}`:""}</small></div></div>)}</div>}{result&&<Pagination page={result.page} pages={result.pages} total={result.total} onChange={setPage}/>}</Panel></>;
}

export function ReportsPage() {
  const [sessions,setSessions]=useState<Session[]>([]); const [sessionId,setSessionId]=useState(0); const [reports,setReports]=useState<any[]>([]); useEffect(()=>{Promise.all([api<PageResult<Session>>("/sessions?page_size=100"),api<any[]>("/reports")]).then(([s,r])=>{setSessions(s.items);setReports(r);if(s.items[0])setSessionId(s.items[0].id);});},[]);
  const selected=sessions.find((s)=>s.id===sessionId); return <><PageHeader eyebrow="DOCUMENTAÇÃO TÉCNICA" title="Central de relatórios" description="Gere arquivos rastreáveis em formatos adequados à análise e apresentação."/><div className="report-layout"><Panel title="Configurar relatório" kicker="NOVA GERAÇÃO"><label className="field"><span>Sessão</span><select value={sessionId} onChange={(e)=>setSessionId(Number(e.target.value))}>{sessions.map((s)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><div className="form-grid"><label className="field"><span>Escopo</span><select><option>Relatório completo</option><option>Resumo executivo</option></select></label><label className="field"><span>Orientação</span><select><option value="landscape">Paisagem</option><option value="portrait">Retrato</option></select></label></div><div className="check-grid"><label><input type="checkbox" defaultChecked/> Indicadores</label><label><input type="checkbox" defaultChecked/> Gráficos</label><label><input type="checkbox" defaultChecked/> Alertas</label><label><input type="checkbox" defaultChecked/> Tabela resumida</label></div><div className="report-buttons"><button className="button primary" disabled={!selected} onClick={()=>download(`/reports/sessions/${sessionId}.pdf`,`sessao-${sessionId}.pdf`)}><FileText/> Gerar PDF</button><button className="button secondary" disabled={!selected} onClick={()=>download(`/reports/sessions/${sessionId}.xlsx`,`sessao-${sessionId}.xlsx`)}><FileSpreadsheet/> Gerar XLSX</button><button className="button ghost" disabled={!selected} onClick={()=>download(`/reports/sessions/${sessionId}.csv`,`sessao-${sessionId}.csv`)}><Download/> Gerar CSV</button></div></Panel><Panel title="Prévia do conteúdo" kicker="SESSÃO SELECIONADA">{selected ? <div className="report-preview"><span className="report-logo"><BellRing/></span><p>RELATÓRIO DE MEDIÇÃO</p><h2>{selected.name}</h2><div><span>Equipamento</span><strong>{selected.device_name}</strong></div><div><span>Operador</span><strong>{selected.operator}</strong></div><div><span>Amostras</span><strong>{selected.sample_count.toLocaleString("pt-BR")}</strong></div><div><span>Alertas</span><strong>{selected.alert_count}</strong></div></div>:<Empty/>}</Panel></div><Panel title="Histórico de geração" kicker="ARQUIVOS RECENTES"><div className="table-scroll"><table><thead><tr><th>Tipo</th><th>Sessão</th><th>Gerado em</th><th>Usuário</th></tr></thead><tbody>{reports.map((r)=><tr key={r.id}><td><Badge>{r.type.toUpperCase()}</Badge></td><td>#{r.session_id}</td><td>{formatDate(r.generated_at)}</td><td>#{r.generated_by}</td></tr>)}</tbody></table></div></Panel></>;
}

export function ComparePage() {
  const [sessions,setSessions]=useState<Session[]>([]); const [selected,setSelected]=useState<number[]>([]); const [data,setData]=useState<any>(null); const [error,setError]=useState(""); useEffect(()=>{api<PageResult<Session>>("/sessions?page_size=100&status=finished").then((r)=>setSessions(r.items));},[]); async function compare(){try{setData(await api(`/statistics/compare?${selected.map((id)=>`session_ids=${id}`).join("&")}`));}catch(err){setError(err instanceof Error?err.message:"Falha");}}
  const chartData=data?.sessions.map((s:any)=>({name:sessions.find((row)=>row.id===s.session_id)?.name ?? `#${s.session_id}`,media:s.power.mean,maxima:s.power.max,tempMax:Math.max(...Object.values(s.temperatures).map((v:any)=>v.max),0),alertas:s.alert_count})); return <><PageHeader eyebrow="ANÁLISE COMPARATIVA" title="Comparação de sessões" description="Sobreponha indicadores de duas a oito sessões e identifique diferenças." actions={<button className="button primary" disabled={selected.length<2} onClick={compare}>Comparar {selected.length} sessões</button>}/>{error&&<ErrorNotice message={error}/>}<Panel title="Selecionar sessões" kicker="AMOSTRA"><div className="session-select-grid">{sessions.map((s)=><label key={s.id} className={selected.includes(s.id)?"selected":""}><input type="checkbox" checked={selected.includes(s.id)} disabled={!selected.includes(s.id)&&selected.length>=8} onChange={()=>setSelected((current)=>current.includes(s.id)?current.filter((id)=>id!==s.id):[...current,s.id])}/><div><strong>{s.name}</strong><span>{s.device_name} · {formatDate(s.started_at)}</span></div><Badge>{s.sample_count} amostras</Badge></label>)}</div></Panel>{chartData&&<><div className="metrics-grid four">{chartData.slice(0,4).map((row:any)=><Metric key={row.name} label={row.name} value={`${(row.media??0).toFixed(1)} W`} hint={`Máx ${(row.maxima??0).toFixed(1)} W · ${row.alertas} alertas`}/>)}</div><div className="charts-grid"><Panel title="Potência por sessão"><div className="chart-container"><ResponsiveContainer width="100%" height="100%"><BarChart data={chartData}><CartesianGrid vertical={false}/><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="media" name="Média (W)" fill="#3b6ef5"/><Bar dataKey="maxima" name="Máxima (W)" fill="#9bb6ff"/></BarChart></ResponsiveContainer></div></Panel><Panel title="Temperatura máxima"><div className="chart-container"><ResponsiveContainer width="100%" height="100%"><BarChart data={chartData}><CartesianGrid vertical={false}/><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="tempMax" name="Temperatura (°C)" fill="#f59e0b"/></BarChart></ResponsiveContainer></div></Panel></div></>}</>;
}

export function UsersPage() {
  const [users,setUsers]=useState<any[]>([]); const [show,setShow]=useState(false); const [error,setError]=useState(""); const load=useCallback(()=>api<any[]>("/users").then(setUsers).catch((e)=>setError(e.message)),[]);useEffect(()=>{void load();},[load]);async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);try{await api("/users",{method:"POST",body:JSON.stringify({name:data.get("name"),email:data.get("email"),password:data.get("password"),role:data.get("role")})});setShow(false);load();}catch(e){setError(e instanceof Error?e.message:"Falha");}}
  return <><PageHeader eyebrow="CONTROLE DE ACESSO" title="Usuários e permissões" description="Perfis separados para administração, operação e consulta." actions={<button className="button primary" onClick={()=>setShow(true)}><UserPlus/> Novo usuário</button>}/>{error&&<ErrorNotice message={error}/>}<div className="metrics-grid three"><Metric label="Administradores" value={users.filter((u)=>u.role==="admin").length}/><Metric label="Operadores" value={users.filter((u)=>u.role==="operator").length}/><Metric label="Visualizadores" value={users.filter((u)=>u.role==="viewer").length}/></div><Panel className="table-panel"><div className="table-scroll"><table><thead><tr><th>Usuário</th><th>E-mail</th><th>Perfil</th><th>Status</th><th>Criado em</th></tr></thead><tbody>{users.map((u)=><tr key={u.id}><td><strong>{u.name}</strong></td><td>{u.email}</td><td><Badge tone={u.role==="admin"?"primary":u.role==="operator"?"success":"neutral"}>{u.role}</Badge></td><td><Badge tone={u.active?"success":"danger"}>{u.active?"Ativo":"Inativo"}</Badge></td><td>{formatDate(u.created_at)}</td></tr>)}</tbody></table></div></Panel>{show&&<div className="modal-backdrop" onMouseDown={()=>setShow(false)}><form className="modal" onSubmit={create} onMouseDown={(e)=>e.stopPropagation()}><div className="modal-head"><div><p className="eyebrow">ACESSO</p><h2>Novo usuário</h2></div><button type="button" onClick={()=>setShow(false)}>×</button></div><label className="field"><span>Nome</span><input name="name" required minLength={2}/></label><label className="field"><span>E-mail</span><input name="email" type="email" required/></label><label className="field"><span>Senha temporária</span><input name="password" type="password" required minLength={10}/></label><label className="field"><span>Perfil</span><select name="role"><option value="viewer">Visualizador</option><option value="operator">Operador</option><option value="admin">Administrador</option></select></label><div className="modal-actions"><button className="button primary"><ShieldCheck/> Criar acesso</button></div></form></div>}</>;
}

export function DiagnosticsPage() {
  const [data,setData]=useState<any>(null); const [error,setError]=useState(""); const load=useCallback(()=>api<any>("/diagnostics").then(setData).catch((e)=>setError(e.message)),[]); useEffect(()=>{load();const id=setInterval(load,5000);return()=>clearInterval(id);},[load]);
  return <><PageHeader eyebrow="SAÚDE DA PLATAFORMA" title="Diagnóstico do sistema" description="Verificações técnicas atualizadas automaticamente a cada cinco segundos." actions={<button className="button secondary" onClick={load}><RefreshCw/> Atualizar</button>}/>{error&&<ErrorNotice message={error}/>} {!data?<Spinner/>:<><div className="health-banner"><span><Check/></span><div><p>SISTEMA OPERACIONAL</p><h2>Todos os serviços essenciais estão respondendo</h2><small>Versão {data.system_version} · Ambiente {data.environment}</small></div></div><div className="diagnostic-grid"><Panel title="Serviços" kicker="INFRAESTRUTURA"><div className="health-list"><div><Server/><span>Backend</span><Badge tone={data.backend_online?"success":"danger"}>{data.backend_online?"Online":"Offline"}</Badge></div><div><Wifi/><span>Banco de dados</span><Badge tone={data.database_online?"success":"danger"}>{data.database_online?`Online · ${data.database_dialect}`:"Offline"}</Badge></div><div><PlugZap/><span>WebSocket</span><Badge tone="success">{data.websocket_clients} cliente(s)</Badge></div></div></Panel><Panel title="Recursos" kicker="CAPACIDADE"><div className="insight-list"><div><span>Espaço disponível</span><strong>{(data.disk_free_bytes/1024/1024/1024).toFixed(1)} GB</strong></div><div><span>Tempo de atividade</span><strong>{Math.floor(data.uptime_seconds/60)} min</strong></div><div><span>Versão do sistema</span><strong>{data.system_version}</strong></div></div></Panel></div><Panel title="Fontes conectadas" kicker="AQUISIÇÃO">{data.devices.length?<div className="table-scroll"><table><thead><tr><th>Equipamento</th><th>Estado</th><th>Última mensagem</th><th>Mensagens/s</th><th>Erros</th><th>Buffer</th></tr></thead><tbody>{data.devices.map((d:any)=><tr key={d.device_id}><td>#{d.device_id}</td><td><Badge tone={d.connected?"success":"neutral"}>{d.state}</Badge></td><td>{formatDate(d.last_message_at)}</td><td>{d.messages_per_second.toFixed(2)}</td><td>{d.read_errors}</td><td>{d.buffered_measurements}</td></tr>)}</tbody></table></div>:<Empty title="Nenhum equipamento conectado"/>}</Panel></>}</>;
}

export function ExecutivePage() {
  const [stats,setStats]=useState<any>(null); const [sessions,setSessions]=useState<Session[]>([]); useEffect(()=>{Promise.all([api("/statistics/executive"),api<PageResult<Session>>("/sessions?page_size=100")]).then(([s,list])=>{setStats(s);setSessions(list.items);});},[]); const severityData=useMemo(()=>[{name:"Com alertas",value:sessions.filter((s)=>s.alert_count).length,color:"#ef4444"},{name:"Sem alertas",value:sessions.filter((s)=>!s.alert_count).length,color:"#22c55e"}],[sessions]); if(!stats)return <Spinner/>; return <><PageHeader eyebrow="INTELIGÊNCIA OPERACIONAL" title="Dashboard executivo" description="Indicadores históricos para gestão de uso, desempenho e confiabilidade." actions={<div className="date-filter">Últimos 30 dias</div>}/><div className="metrics-grid four"><Metric label="Total de sessões" value={stats.total_sessions.toLocaleString("pt-BR")} hint="Histórico completo" tone="primary"/><Metric label="Horas monitoradas" value={stats.monitored_hours.toFixed(1)} hint="Tempo consolidado"/><Metric label="Total de amostras" value={stats.total_samples.toLocaleString("pt-BR")} hint="Medições persistidas"/><Metric label="Alertas gerados" value={stats.total_alerts.toLocaleString("pt-BR")} hint="Todas as severidades" tone={stats.total_alerts?"danger":"default"}/></div><div className="charts-grid"><Panel title="Potência média por sessão" kicker="TENDÊNCIA"><div className="chart-container"><ResponsiveContainer width="100%" height="100%"><BarChart data={sessions.slice(0,12).reverse()}><CartesianGrid vertical={false}/><XAxis dataKey="name" hide/><YAxis/><Tooltip/><Bar dataKey="average_power_w" name="Potência média (W)" fill="#3b6ef5" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></Panel><Panel title="Qualidade das sessões" kicker="ALERTAS"><div className="chart-container"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={severityData} dataKey="value" nameKey="name" innerRadius={62} outerRadius={94} paddingAngle={4}>{severityData.map((row)=><Cell key={row.name} fill={row.color}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div></Panel></div><Panel title="Sessões recentes" kicker="ATIVIDADE"><div className="table-scroll"><table><thead><tr><th>Sessão</th><th>Equipamento</th><th>Operador</th><th>Amostras</th><th>Potência média</th><th>Temp. máxima</th><th>Alertas</th></tr></thead><tbody>{sessions.slice(0,8).map((s)=><tr key={s.id}><td><strong>{s.name}</strong></td><td>{s.device_name}</td><td>{s.operator}</td><td>{s.sample_count}</td><td>{s.average_power_w?.toFixed(1)??"—"} W</td><td>{s.maximum_temperature_c?.toFixed(1)??"—"} °C</td><td><Badge tone={s.alert_count?"danger":"success"}>{s.alert_count}</Badge></td></tr>)}</tbody></table></div></Panel></>;
}
