import { Columns3, Download, Eye, Filter } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { api, download, formatDate } from "../api";
import { Badge, Empty, ErrorNotice, PageHeader, Pagination, Panel, Spinner } from "../components/ui";
import type { PageResult, Session } from "../types";

export default function MeasurementsPage() {
  const [sessions, setSessions] = useState<Session[]>([]); const [sessionId, setSessionId] = useState(0); const [page, setPage] = useState(1); const [result, setResult] = useState<PageResult<any> | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [showAll, setShowAll] = useState(false);
  useEffect(() => { api<PageResult<Session>>("/sessions?page_size=100").then((data) => { setSessions(data.items); if (data.items[0]) setSessionId(data.items[0].id); }); }, []);
  const load = useCallback(() => { if (!sessionId) return; setLoading(true); api<PageResult<any>>(`/measurements?session_id=${sessionId}&page=${page}&page_size=50`).then(setResult).catch((err) => setError(err.message)).finally(() => setLoading(false)); }, [sessionId, page]);
  useEffect(load, [load]);
  return <><PageHeader eyebrow="DADOS BRUTOS" title="Tabela de medições" description="Registros paginados pelo backend, com potência original e normalizada." actions={<button className="button secondary" disabled={!sessionId} onClick={() => download(`/reports/sessions/${sessionId}.csv`, `sessao-${sessionId}.csv`)}><Download /> Exportar CSV</button>} />{error && <ErrorNotice message={error} retry={load}/>}<Panel className="filter-panel"><div className="filters"><label><Filter/><select value={sessionId} onChange={(e) => { setSessionId(Number(e.target.value)); setPage(1); }}>{sessions.map((session) => <option key={session.id} value={session.id}>{session.name}</option>)}</select></label><button className="button ghost" onClick={() => setShowAll(!showAll)}><Columns3/> {showAll ? "Ocultar T5–T16" : "Exibir 16 canais"}</button></div></Panel><Panel className="table-panel">{loading ? <Spinner label="Carregando medições"/> : !result?.items.length ? <Empty title="A sessão ainda não possui medições"/> : <div className="table-scroll sticky"><table><thead><tr><th>Timestamp</th><th>Potência original</th><th>Potência em W</th>{Array.from({length: showAll ? 16 : 4}, (_, i) => <th key={i}>T{i + 1}</th>)}<th>Qualidade</th><th>Alerta</th><th/></tr></thead><tbody>{result.items.map((row) => <tr key={row.id}><td>{formatDate(row.timestamp)}</td><td>{row.raw_power.toLocaleString("pt-BR")} {row.raw_power_unit}</td><td><strong>{row.power_w.toFixed(3)} W</strong></td>{Array.from({length: showAll ? 16 : 4}, (_, i) => <td key={i}>{row.temperatures[String(i + 1)] != null ? `${row.temperatures[String(i + 1)].toFixed(2)} °C` : "—"}</td>)}<td><Badge tone={row.quality === "good" ? "success" : "warning"}>{row.quality === "good" ? "Válida" : row.quality}</Badge></td><td>{row.has_alert ? <Badge tone="danger">Sim</Badge> : "—"}</td><td><button className="icon-button"><Eye/></button></td></tr>)}</tbody></table></div>}{result && <Pagination page={result.page} pages={result.pages} total={result.total} onChange={setPage}/>}</Panel></>;
}
