import { Copy, Download, Eye, Filter, Pause, Play, Plus, Search, Square, Trash2 } from "lucide-react";
import { type FormEvent, useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api, download, formatDate, formatDuration } from "../api";
import { useAuth } from "../auth";
import { Badge, Empty, ErrorNotice, PageHeader, Pagination, Panel, Spinner } from "../components/ui";
import type { Device, PageResult, Session } from "../types";

const statusLabel: Record<string, string> = { running: "Em execução", paused: "Pausada", finished: "Finalizada", cancelled: "Cancelada", draft: "Rascunho" };

export default function SessionsPage() {
  const { user } = useAuth();
  const [result, setResult] = useState<PageResult<Session> | null>(null);
  const [devices, setDevices] = useState<Device[]>([]);
  const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const [status, setStatus] = useState("");
  const [showCreate, setShowCreate] = useState(false); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const load = useCallback(() => { setLoading(true); api<PageResult<Session>>(`/sessions?page=${page}&page_size=15&search=${encodeURIComponent(search)}&status=${status}`).then(setResult).catch((err) => setError(err.message)).finally(() => setLoading(false)); }, [page, search, status]);
  useEffect(load, [load]);
  useEffect(() => { api<Device[]>("/devices").then(setDevices); }, []);
  async function transition(id: number, action: string) { try { await api(`/sessions/${id}/${action}`, { method: "POST" }); load(); } catch (err) { setError(err instanceof Error ? err.message : "Falha"); } }
  async function remove(id: number) { if (!confirm("Excluir esta sessão e suas medições?")) return; try { await api(`/sessions/${id}`, { method: "DELETE" }); load(); } catch (err) { setError(err instanceof Error ? err.message : "Falha"); } }
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const optionalId = (name: string) => data.get(name) ? Number(data.get(name)) : undefined; try { await api("/sessions", { method: "POST", body: JSON.stringify({ device_id: optionalId("device"), temperature_device_id: optionalId("temperature_device"), electrical_device_id: optionalId("electrical_device"), name: data.get("name"), description: data.get("description"), notes: data.get("notes"), sample_interval_ms: Number(data.get("interval")), sync_grid_ms: 1000, sync_tolerance_ms: 1500 }) }); setShowCreate(false); load(); } catch (err) { setError(err instanceof Error ? err.message : "Falha"); } }
  return <><PageHeader eyebrow="GESTÃO DE ENSAIOS" title="Sessões de medição" description="Acompanhe, filtre e gerencie todo o histórico de coletas." actions={user?.role !== "viewer" && <button className="button primary" onClick={() => setShowCreate(true)}><Plus /> Nova sessão</button>} />
    {error && <ErrorNotice message={error} retry={load} />}
    <Panel className="filter-panel"><div className="filters"><label className="search-field"><Search /><input placeholder="Pesquisar sessão…" value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} /></label><label><Filter /><select value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }}><option value="">Todos os status</option><option value="running">Em execução</option><option value="paused">Pausadas</option><option value="finished">Finalizadas</option><option value="cancelled">Canceladas</option></select></label></div></Panel>
    <Panel className="table-panel">{loading ? <Spinner label="Consultando sessões" /> : !result?.items.length ? <Empty title="Nenhuma sessão encontrada" text="Altere os filtros ou inicie uma nova coleta." /> : <div className="table-scroll"><table><thead><tr><th>Sessão</th><th>Status</th><th>Equipamento</th><th>Operador</th><th>Início</th><th>Duração</th><th>Amostras</th><th>Potência média</th><th>Temp. máxima</th><th>Alertas</th><th aria-label="Ações" /></tr></thead><tbody>{result.items.map((session) => <tr key={session.id}><td><strong>{session.name}</strong><small>#{session.id}</small></td><td><Badge tone={session.status === "running" ? "success" : session.status === "paused" ? "warning" : session.status === "cancelled" ? "danger" : "neutral"}>{statusLabel[session.status] ?? session.status}</Badge></td><td>{session.device_name}</td><td>{session.operator}</td><td>{formatDate(session.started_at)}</td><td>{formatDuration(session.duration_seconds)}</td><td>{session.sample_count.toLocaleString("pt-BR")}</td><td>{session.average_power_w != null ? `${session.average_power_w.toFixed(1)} W` : "—"}</td><td>{session.maximum_temperature_c != null ? `${session.maximum_temperature_c.toFixed(1)} °C` : "—"}</td><td><Badge tone={session.alert_count ? "danger" : "neutral"}>{session.alert_count}</Badge></td><td><div className="row-actions"><Link title="Abrir detalhes" to={`/sessoes/${session.id}`}><Eye /></Link>{user?.role !== "viewer" && session.status === "running" && <button title="Pausar" onClick={() => transition(session.id, "pause")}><Pause /></button>}{user?.role !== "viewer" && session.status === "paused" && <button title="Continuar" onClick={() => transition(session.id, "resume")}><Play /></button>}{user?.role !== "viewer" && ["running", "paused"].includes(session.status) && <button title="Finalizar" onClick={() => transition(session.id, "finish")}><Square /></button>}<button title="Exportar CSV" onClick={() => download(`/reports/sessions/${session.id}.csv`, `sessao-${session.id}.csv`)}><Download /></button>{user?.role !== "viewer" && <button title="Duplicar" onClick={() => transition(session.id, "duplicate")}><Copy /></button>}{user?.role === "admin" && !["running", "paused"].includes(session.status) && <button title="Excluir" onClick={() => remove(session.id)}><Trash2 /></button>}</div></td></tr>)}</tbody></table></div>}{result && <Pagination page={result.page} pages={result.pages} total={result.total} onChange={setPage} />}</Panel>
    {showCreate && <div className="modal-backdrop" role="presentation" onMouseDown={() => setShowCreate(false)}><form className="modal" onMouseDown={(e) => e.stopPropagation()} onSubmit={create}><div className="modal-head"><div><p className="eyebrow">NOVA COLETA</p><h2>Iniciar sessão de medição</h2></div><button type="button" onClick={() => setShowCreate(false)}>×</button></div><label className="field"><span>Nome da sessão</span><input name="name" placeholder="Ex.: Ensaio térmico do lote A" required minLength={2} /></label><div className="form-grid"><label className="field"><span>Temperatura (AT4532, opcional)</span><select name="temperature_device" defaultValue=""><option value="">Não usar</option>{devices.filter((device) => /at4532|temperat/i.test(`${device.name} ${device.model} ${device.protocol}`)).map((device) => <option value={device.id} key={device.id}>{device.name}</option>)}</select></label><label className="field"><span>Elétrica (GPM-8213, opcional)</span><select name="electrical_device" defaultValue=""><option value="">Não usar</option>{devices.filter((device) => /gpm|8213|electric/i.test(`${device.name} ${device.model} ${device.protocol}`)).map((device) => <option value={device.id} key={device.id}>{device.name}</option>)}</select></label></div><label className="field"><span>Equipamento combinado/simulador (alternativa)</span><select name="device" defaultValue=""><option value="">Não usar</option>{devices.filter((device) => !/at4532|gpm|8213/i.test(`${device.name} ${device.model} ${device.protocol}`)).map((device) => <option value={device.id} key={device.id}>{device.name}</option>)}</select></label><label className="field"><span>Descrição</span><textarea name="description" rows={3} /></label><label className="field"><span>Observações</span><textarea name="notes" rows={2} /></label><label className="field"><span>Intervalo de aquisição</span><select name="interval" defaultValue="1000"><option value="250">250 ms</option><option value="500">500 ms</option><option value="1000">1 segundo</option><option value="2000">2 segundos</option></select></label><div className="modal-actions"><button type="button" className="button ghost" onClick={() => setShowCreate(false)}>Cancelar</button><button className="button primary"><Play /> Conectar e iniciar</button></div></form></div>}
  </>;
}
