import { AlertTriangle, ArrowLeft, Download, FileSpreadsheet, FileText } from "lucide-react";
import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { api, download, formatDate, formatDuration } from "../api";
import { Badge, Empty, ErrorNotice, Metric, PageHeader, Panel, Spinner } from "../components/ui";

export default function SessionDetailPage() {
  const { id } = useParams();
  const [session, setSession] = useState<any>(null); const [series, setSeries] = useState<any[]>([]); const [alerts, setAlerts] = useState<any[]>([]); const [error, setError] = useState("");
  useEffect(() => { Promise.all([api<any>(`/sessions/${id}`), api<any>(`/measurements/series?session_id=${id}&max_points=800`), api<any>(`/alerts?page_size=100`)]).then(([detail, chart, allAlerts]) => { setSession(detail); setSeries(chart.points.map((point: any) => ({ ...point, time: new Date(point.timestamp).toLocaleTimeString("pt-BR") }))); setAlerts(allAlerts.items.filter((alert: any) => alert.session_id === Number(id))); }).catch((err) => setError(err.message)); }, [id]);
  if (error) return <ErrorNotice message={error} />;
  if (!session) return <Spinner label="Carregando análise da sessão" />;
  const stats = session.statistics;
  return <><Link to="/sessoes" className="back-link"><ArrowLeft /> Voltar para sessões</Link><PageHeader eyebrow="ANÁLISE DA SESSÃO" title={session.name} description={`${session.device.name} · ${session.operator.name}`} actions={<><button className="button ghost" onClick={() => download(`/reports/sessions/${id}.csv`, `sessao-${id}.csv`)}><Download /> CSV</button><button className="button secondary" onClick={() => download(`/reports/sessions/${id}.xlsx`, `sessao-${id}.xlsx`)}><FileSpreadsheet /> XLSX</button><button className="button primary" onClick={() => download(`/reports/sessions/${id}.pdf`, `sessao-${id}.pdf`)}><FileText /> PDF</button></>} />
    <div className="detail-strip"><div><span>STATUS</span><Badge tone={session.status === "finished" ? "success" : "warning"}>{session.status}</Badge></div><div><span>PERÍODO</span><strong>{formatDate(session.started_at)} → {formatDate(session.ended_at)}</strong></div><div><span>DURAÇÃO</span><strong>{formatDuration(stats.duration_seconds)}</strong></div><div><span>INTERVALO NOMINAL</span><strong>{session.sample_interval_ms} ms</strong></div></div>
    <div className="metrics-grid six"><Metric label="Medições" value={stats.power.count.toLocaleString("pt-BR")} hint={`${stats.actual_frequency_hz.toFixed(2)} Hz reais`} /><Metric label="Potência média" value={`${(stats.power.mean ?? 0).toFixed(1)} W`} hint={`Mediana ${(stats.power.median ?? 0).toFixed(1)} W`} tone="primary"/><Metric label="Potência máxima" value={`${(stats.power.max ?? 0).toFixed(1)} W`} hint={`Mín ${(stats.power.min ?? 0).toFixed(1)} W`} /><Metric label="Canal mais quente" value={stats.hottest_channel ? `T${stats.hottest_channel}` : "—"} hint="Maior temperatura" tone="warm"/><Metric label="Alertas" value={stats.alert_count} hint="Violações registradas" tone={stats.alert_count ? "danger" : "default"}/><Metric label="Lacunas" value={stats.acquisition_gaps} hint={`${stats.channels_without_readings.length} canais sem leitura`} /></div>
    <div className="charts-grid"><Panel title="Curva de potência" kicker="SÉRIE TEMPORAL AGREGADA"><div className="chart-container tall"><ResponsiveContainer width="100%" height="100%"><AreaChart data={series}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="time" minTickGap={40}/><YAxis unit=" W"/><Tooltip/><Area type="monotone" dataKey="power_w" stroke="#3b6ef5" fill="#dbe6ff" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></Panel><Panel title="Diagnóstico automático" kicker="QUALIDADE DOS DADOS"><div className="insight-list"><div><span>Maior variação</span><strong>{stats.highest_variation_channel ? `Termopar T${stats.highest_variation_channel}` : "Sem dados"}</strong></div><div><span>Canal mais frio</span><strong>{stats.coldest_channel ? `Termopar T${stats.coldest_channel}` : "Sem dados"}</strong></div><div><span>Desvio padrão da potência</span><strong>{(stats.power.stddev ?? 0).toFixed(2)} W</strong></div><div><span>Percentil 95 da potência</span><strong>{(stats.power.p95 ?? 0).toFixed(2)} W</strong></div><div><span>Canais sem leitura</span><strong>{stats.channels_without_readings.length ? stats.channels_without_readings.map((c: number) => `T${c}`).join(", ") : "Nenhum"}</strong></div></div></Panel></div>
    <Panel title="Estatísticas por termopar" kicker="COMPARAÇÃO ENTRE CANAIS"><div className="channel-stat-grid">{Object.entries(stats.temperatures).map(([channel, value]: any) => <div key={channel}><span>T{channel}</span><strong>{value.mean.toFixed(1)} °C</strong><small>Mín {value.min.toFixed(1)} · Máx {value.max.toFixed(1)} · σ {value.stddev.toFixed(2)}</small></div>)}</div></Panel>
    <Panel title="Alertas da sessão" kicker="VIOLAÇÕES"><div className="alert-list">{alerts.length ? alerts.map((alert) => <div key={alert.id}><AlertTriangle /><div><strong>{alert.metric === "power" ? "Potência" : `Termopar T${alert.channel}`}</strong><span>{alert.measured_value.toFixed(2)} · limite {alert.threshold}</span></div><Badge tone={alert.severity === "critical" ? "danger" : "warning"}>{alert.severity}</Badge><time>{formatDate(alert.timestamp)}</time></div>) : <Empty title="Nenhum alerta nesta sessão" />}</div></Panel>
  </>;
}
